### PR TITLE
Add search input in Badges and Docs pages #47

### PR DESCRIPTION
**Pull request by Ali-Sdg90**

### CODE REVIEW

**Comment by hootanht** [comment]
Thanks @Ali-Sdg90. Can you please attach a screenshot here for implementing this feature?

**Comment by Ali-Sdg90** [comment]
Sure!

Screenshot 2024-03-02 005208
Screenshot 2024-03-02 005225

**Comment by hootanht** [comment]
The search box design is a key element of the user interface. We agreed that it should be placed on the left side of the screen, but the current implementation has it on the center of the top component. This is not consistent with our design guidelines and may confuse the users. Moreover, the search button icon should be integrated into the input field, rather than being a separate button outside of it. This would make the search box more compact and elegant.
@Ali-Sdg90

**Comment by Ali-Sdg90** [comment]
The task didn't specify that the search bar needed to be left-aligned, and I don't recall discussing it.
I've aligned it to the left and sent the pull request.

@hootanht 

Screenshot 2024-03-02 142518
Screenshot 2024-03-02 142619

**Comment by hootanht** [comment]
It's good for now, but if we can add an icon in input, like search input is better. Approve that but in the future, we add a search icon in the input.

**Comment by Ali-Sdg90** [comment]
> It's good for now, but if we can add an icon in input, like search input is better. Approve that but in the future, we add a search icon in the input.

Thank you. I think I don't understand correctly. You said it's appropriate for now, and you will merge the pull request, and later we'll add the search icon to the search bar. But the pull request hasn't been merged into the develop branch yet.

**Comment by hootanht** [comment]
> > It's good for now, but if we can add an icon in input, like search input is better. Approve that but in the future, we add a search icon in the input.
> 
> Thank you. I think I don't understand correctly. You said it's appropriate for now, and you will merge the pull request, and later we'll add the search icon to the search bar. But the pull request hasn't been merged into the develop branch yet. I would appreciate it if you could clarify my confusion.

Have you noticed the comments on my reviews?

**Pull request merged**
